//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedbackAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feed
    {
        public int sno { get; set; }
        public string MRNO { get; set; }
        public string Patient_feeds { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Dt { get; set; }
        public string Reasons { get; set; }
        public string Name { get; set; }
    }
}
