//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIOSK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country_Master
    {
        public string COUNTRY_CODE { get; set; }
        public string COUNTRY_NAME { get; set; }
        public string TOTAL_MALE_POPULATION { get; set; }
        public string TOTAL_FEMALE_POPULATION { get; set; }
        public string TOTAL_MALE_EYE_DEFECT_POPULATION { get; set; }
        public string TOTAL_FEMALE_EYE_DEFECT_POPULATION { get; set; }
        public string country_grp { get; set; }
    }
}
