//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIOSK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class District_Master
    {
        public string DISTRICT_CODE { get; set; }
        public string DISTRICT_NAME { get; set; }
        public string STATE_CODE { get; set; }
        public Nullable<double> TOTAL_MALE_POPULATION { get; set; }
        public Nullable<double> TOTAL_FEMALE_POPULATION { get; set; }
        public Nullable<double> PERCENTAGE_OF_TOTAL_MALE_EYE_DEFECT_POPULATION { get; set; }
        public Nullable<double> PERCENTAGE_OF_TOTAL_FEMALE_EYE_DEFECT_POPULATION { get; set; }
        public string GIS_CODE { get; set; }
        public string district_grp { get; set; }
    }
}
