//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIOSK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taluk_Master
    {
        public string TALUK_CODE { get; set; }
        public string TALUK_NAME { get; set; }
        public string DISTRICT_CODE { get; set; }
        public string GIS_CODE { get; set; }
        public string taluk_grp { get; set; }
    }
}
