//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int PIN { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Gender { get; set; }
        public string Nextofkin { get; set; }
        public Nullable<System.DateTime> Dt { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string LandlineNo { get; set; }
        public string Address { get; set; }
        public string Locality { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public string Taluk { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Visit { get; set; }
        public string MRNO { get; set; }
    }
}
